# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20180910_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_picture/None/blank-profile.png', upload_to='profile_picture/'),
        ),
    ]
