# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-19 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180914_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendsignup',
            name='coin_choices',
            field=models.TextField(default='', max_length=300),
        ),
    ]
