# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-19 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_extendsignup_coin_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendsignup',
            name='coin_choices',
            field=models.TextField(null=True),
        ),
    ]
