# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20180919_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=5)),
                ('price', models.FloatField(null=True)),
                ('percentage_change_1h', models.FloatField(null=True)),
                ('percentage_change_24h', models.FloatField(null=True)),
                ('percentage_change_7d', models.FloatField(null=True)),
                ('volume_24h', models.FloatField(null=True)),
                ('market_capital', models.FloatField(null=True)),
            ],
        ),
    ]
