# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-23 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20180923_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindetails',
            name='market_capital',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='percent_change_1h',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='percent_change_24h',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='percent_change_7d',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='price',
            field=models.FloatField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='coindetails',
            name='volume_24h',
            field=models.FloatField(max_length=200, null=True),
        ),
    ]
