# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-23 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180923_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coindetails',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
