# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-23 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20180923_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coindetails',
            old_name='market_capital',
            new_name='market_cap',
        ),
    ]
