# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-08 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180923_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=1000)),
                ('image_url', models.URLField(max_length=300)),
                ('published_at', models.DateTimeField()),
                ('source_domain', models.URLField(max_length=50)),
            ],
        ),
    ]
